### ISSUE TITLE
Getting errors on installing dependencies

### ISSUE THREAD

**Issue by hasnat23** [dshubhadeep/devote#1]
I am getting a lot of errors after executing "npm i" command. Can you Please help me to successfully execute this code without getting errors?
![Capture](https://user-images.githubusercontent.com/49604635/68469434-fda50d80-023b-11ea-9de3-693adcdd8f20.PNG)

**Comment by dshubhadeep** [comment]
@hasnat23 You might face installation errors in Windows. 

You can refer to this [issue](https://github.com/ethereum/web3.js/issues/1783). This requires installing windows build tools. This is not a 100% guaranteed solution.
Or you can try installing [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10). This will serve you better in the long run.

**Comment by hasnat23** [comment]
Hello bro Thanks for your reply. Can you please tell me should I use Ubuntu
Linux on virtual box(in windows) for running this project or it can be
easily run on Windows 10.

Your help is much appreciated.

**Comment by dshubhadeep** [comment]
You can run it on windows 10 if you install WSL. See this [link](https://docs.microsoft.com/en-us/windows/wsl/install-win10)

**Comment by hasnat23** [comment]
Okay, Thank you. I will try this out. I hope this works.

**Comment by hasnat23** [comment]
Hello bro, I am done with the installation of Ubuntu on Windows provided the link by you. Now, what's the next step. I didn't work much on Linux. Can you Please guide me on how to install dependencies using Linux CLI. 
![Capture](https://user-images.githubusercontent.com/49604635/68529432-91e8a080-0320-11ea-9761-559e6714c1fa.PNG)

**Comment by hasnat23** [comment]
Still getting these errors. After executing "npm i" command.

$ npm i

> sha3@1.2.3 install C:\Users\Ch Muhammad Hasnat\Desktop\Final\Proj-1\devote\node_modules\sha3
> node-gyp rebuild


C:\Users\Ch Muhammad Hasnat\Desktop\Final\Proj-1\devote\node_modules\sha3>if not defined npm_config_node_gyp (node "C:\Users\Ch Muhammad Hasnat\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Ch Muhammad Hasnat\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! find VS
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS checking VS2017 (15.9.28307.145) found at:
gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
gyp ERR! find VS - found "Visual Studio C++ core features"
gyp ERR! find VS - missing any VC++ toolset
gyp ERR! find VS checking VS2017 (15.8.28010.2019) found at:
gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community"
gyp ERR! find VS - found "Visual Studio C++ core features"
gyp ERR! find VS - missing any VC++ toolset
gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\Ch Muhammad Hasnat\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at C:\Users\Ch Muhammad Hasnat\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\Ch Muhammad Hasnat\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:344:14)
gyp ERR! stack     at C:\Users\Ch Muhammad Hasnat\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
gyp ERR! stack     at C:\Users\Ch Muhammad Hasnat\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:365:16
gyp ERR! stack     at C:\Users\Ch Muhammad Hasnat\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\Users\Ch Muhammad Hasnat\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16gyp ERR! stack     at ChildProcess.exithandler (child_process.js:302:5)
gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Ch Muhammad Hasnat\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Ch Muhammad Hasnat\Desktop\Final\Proj-1\devote\node_modules\sha3
gyp ERR! node -v v12.10.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sha3@1.2.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sha3@1.2.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ch Muhammad Hasnat\AppData\Roaming\npm-cache\_logs\2019-11-09T13_44_47_434Z-debug.log

**Comment by dshubhadeep** [comment]
You'll need to install node first. Check this [link](https://gist.github.com/noygal/6b7b1796a92d70e24e35f94b53722219)

You'll need to run this on the linux cli (not git bash)

**Comment by hasnat23** [comment]
Hello bro, Can you Please spare 5 mins to help me run this project successfully by using Team Viewer. I shall be glad for you. I am still getting errors after implementing the above solution. 

How can we get connected?

**Comment by dshubhadeep** [comment]
What problems are you facing ?

**Comment by hasnat23** [comment]
I have followed every step on this page. [https://gist.github.com/noygal/6b7b1796a92d70e24e35f94b53722219](url)

But After Executing "npm i" command on VS Code (git bash) I am still getting same errors.
![Capture](https://user-images.githubusercontent.com/49604635/68531540-2826c180-0335-11ea-8134-c52ae6e008be.PNG)

**Comment by dshubhadeep** [comment]
**Do not use git bash**
Use this terminal https://github.com/dshubhadeep/devote/issues/1#issuecomment-552101475

**Comment by hasnat23** [comment]
You mean Access project folder using Ubuntu CLI and then run "npm i" command. Am I right?

Can you please tell me a command to access the project folder using Ubuntu?

**Comment by dshubhadeep** [comment]
Yes

Open Ubuntu CLI and type the following command

```bash
cd  /mnt/c/Users/<your name>/Desktop/Final/
```

**Comment by hasnat23** [comment]
Sorry bro I might be disturbing you. But I am still stuck in it. It's showing me too many arguments error.
![Capture](https://user-images.githubusercontent.com/49604635/68531743-7d63d280-0337-11ea-8875-92b1a15c6f02.PNG)

**Comment by dshubhadeep** [comment]
Type cd /mnt/c/Users/C

Then press tab for autocomplete

**Comment by hasnat23** [comment]
Thanks mate. I have reached project folder. When I put "npm i" command its showing me an error. What's the next step.
![Capture](https://user-images.githubusercontent.com/49604635/68531892-34ad1900-0339-11ea-8e31-54aae0a096dd.PNG)

**Comment by dshubhadeep** [comment]
What is the output for the following commands ?

```bash
node -v
npm -v
which node
which npm
```

**Comment by hasnat23** [comment]
After Executing node -v:

Command 'node' not found, but can be installed with:

sudo apt install nodejs

After Executing npm -v:

: not foundram Files/nodejs/npm: 3: /mnt/c/Program Files/nodejs/npm:
: not foundram Files/nodejs/npm: 5: /mnt/c/Program Files/nodejs/npm:
/mnt/c/Program Files/nodejs/npm: 6: /mnt/c/Program Files/nodejs/npm: Syntax error: word unexpected (expecting "in")

**Comment by hasnat23** [comment]
No output for "which node" command .

for "which npm" : just showed this line /mnt/c/Program Files/nodejs/npm

**Comment by dshubhadeep** [comment]
Try restarting the terminal and run the command again

If it doesn't work, it means node is not installed on your machine
Follow this again https://gist.github.com/noygal/6b7b1796a92d70e24e35f94b53722219 
and type the commands on your Ubuntu CLI (not git bash)

Note : Install node v10.x. Web3 has installation issues on node v12
Use `nvm install 10.16.3` instead of `nvm install --lts`

**Comment by hasnat23** [comment]
I have now successfully installed node. Now using node v10.16.3 (npm v6.9.0)

**Comment by hasnat23** [comment]
All the dependencies have been installed succesfully except.
husky > Failed to install

I did not understand this line written in description:  
**Note**: Ensure ganache-cli is running at port 8545
Is there any command to run ganache-cli before executing this project?

**Comment by dshubhadeep** [comment]
Yes, you need to install `ganache-cli` **globally** using npm

2 Ubuntu CLI should be open
One should be running ganache (start by typing ganache-cli)
For the second, you can run the setup script using
`./setup.sh`
and then run `npm run dev`

**Comment by hasnat23** [comment]
what's the command for installing ganache-cli globally?

After installing ganache-cli, which command I will run. ist it "run ganache-cli"?

After that I have to switch directory to ./setup.sh then run npm run dev.
am I right?

Thank you so much for your help and precious time :)

**Comment by dshubhadeep** [comment]
npm i -g ganache-cli

There is a script
Run it using typing ./setup.sh

**Comment by hasnat23** [comment]
The project run successfully. Can you Please share design document for this project so that I can understand workflow process? I want to convert this project into a student union election project with registration process and casting vote on blockchain network. Is it possibe to reuse this project according to my requirements?

Can you Please guide me in this regards. Thank you

**Comment by hasnat23** [comment]
Again I got this error when I clicked on the register button.
![Capture](https://user-images.githubusercontent.com/49604635/68533370-befd7900-0349-11ea-92aa-3ed6cfa37d94.PNG)

**Comment by hasnat23** [comment]
When I clicked on create compaign. got this error: 

No "from" address specified in neither the given options, nor the default options.

**Comment by dshubhadeep** [comment]
> Can you Please share design document for this project so that I can understand workflow process?

I will update the README by tomorrow.

> I want to convert this project into a student union election project with registration process and casting vote on blockchain network. Is it possibe to reuse this project according to my requirements?

Yeah, it is possible. But this project is limited to only local development. I don't think it will be possible to deploy it to any public network because of the high gas cost.


You need to install [Metamask](https://metamask.io/) and add the mnemonic provided by ganache-cli using **Import seed phrase** in Metamask. 

If you are facing problems using ganache-cli, you can also use the GUI. Check [link](https://www.trufflesuite.com/ganache)

**Comment by dshubhadeep** [comment]
@hasnat23 I'm closing this issue. Feel free to open a new one if you face any problems.
